// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class SpellConstruction
{
    public static class Book
    {
        private static FormLink<IBookGetter> Construct(uint id) => new FormLink<IBookGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBookGetter> SCConstructionAlteration => Construct(0xd62);
        public static FormLink<IBookGetter> SCConstructionConjuration => Construct(0xd63);
        public static FormLink<IBookGetter> SCConstructionDestruction => Construct(0xd64);
        public static FormLink<IBookGetter> SCConstructionIllusion => Construct(0xd65);
        public static FormLink<IBookGetter> SCConstructionRestoration => Construct(0xd66);
        public static FormLink<IBookGetter> SCConstructionSelf => Construct(0xd67);
        public static FormLink<IBookGetter> SCConstructionTouch => Construct(0xd68);
        public static FormLink<IBookGetter> SCConstructionTarget => Construct(0xd69);
        public static FormLink<IBookGetter> SCConstructionConcentration => Construct(0xd6b);
        public static FormLink<IBookGetter> SCConstructionFireAndForget => Construct(0xd6c);
        public static FormLink<IBookGetter> SCConstructionAspectArmor => Construct(0xd6d);
        public static FormLink<IBookGetter> SCConstructionAspectHeat => Construct(0xd6e);
        public static FormLink<IBookGetter> SCConstructionAspectCold => Construct(0xd6f);
        public static FormLink<IBookGetter> SCConstructionAspectShock => Construct(0xd70);
        public static FormLink<IBookGetter> SCConstructionAspectPoison => Construct(0xd71);
        public static FormLink<IBookGetter> SCConstructionAspectLove => Construct(0xd72);
        public static FormLink<IBookGetter> SCConstructionAspectFear => Construct(0xd73);
        public static FormLink<IBookGetter> SCConstructionAspectAnger => Construct(0xd74);
        public static FormLink<IBookGetter> SCConstructionAspectVisibility => Construct(0xd76);
        public static FormLink<IBookGetter> SCConstructionAspectParalysis => Construct(0xd77);
        public static FormLink<IBookGetter> SCConstructionAspectUndead => Construct(0xd78);
        public static FormLink<IBookGetter> SCConstructionAspectDaedra => Construct(0xd79);
        public static FormLink<IBookGetter> SCConstructionAspectDisease => Construct(0xd7a);
        public static FormLink<IBookGetter> SCConstructionAspectTime => Construct(0xd7b);
        public static FormLink<IBookGetter> SCConstructionAspectForce => Construct(0xd7c);
        public static FormLink<IBookGetter> SCConstructionAspectLight => Construct(0xd7d);
        public static FormLink<IBookGetter> SCConstructionAspectDark => Construct(0xd7e);
        public static FormLink<IBookGetter> SCConstructionAspectSpeed => Construct(0xd7f);
        public static FormLink<IBookGetter> SCConstructionAspectWater => Construct(0xd80);
        public static FormLink<IBookGetter> SCConstructionAspectAir => Construct(0xd81);
        public static FormLink<IBookGetter> SCConstructionAspectSpirit => Construct(0xd82);
        public static FormLink<IBookGetter> SCConstructionAspectSoul => Construct(0xd83);
        public static FormLink<IBookGetter> SCConstructionAspectSound => Construct(0xd84);
        public static FormLink<IBookGetter> SCConstructionAspectHealth => Construct(0xd85);
        public static FormLink<IBookGetter> SCConstructionAspectStamina => Construct(0xd86);
        public static FormLink<IBookGetter> SCConstructionAspectMagicka => Construct(0xd87);
        public static FormLink<IBookGetter> SCConstructionAspectWeapon => Construct(0xd88);
        public static FormLink<IBookGetter> SCConstructionAspectMass => Construct(0xd89);
        public static FormLink<IBookGetter> SCConstructionAspectDevice => Construct(0xd8a);
        public static FormLink<IBookGetter> SCConstructionAspectEarth => Construct(0xd8b);
        public static FormLink<IBookGetter> SCConstructionAspectMind => Construct(0xd8c);
        public static FormLink<IBookGetter> SCConstructionAspectBody => Construct(0xd8d);
        public static FormLink<IBookGetter> SCConstructionAspectShadow => Construct(0xd8e);
        public static FormLink<IBookGetter> SCConstructionAspectCloak => Construct(0xd8f);
        public static FormLink<IBookGetter> SCConstructionAspectDamage => Construct(0xd90);
        public static FormLink<IBookGetter> SCConstructionAspectHeal => Construct(0xd91);
        public static FormLink<IBookGetter> SCConstructionAspectInfluence => Construct(0xd92);
        public static FormLink<IBookGetter> SCConstructionAspectRune => Construct(0xd93);
        public static FormLink<IBookGetter> SCConstructionAspectSummon => Construct(0xd94);
        public static FormLink<IBookGetter> SCConstructionAspectBind => Construct(0xd95);
        public static FormLink<IBookGetter> SCConstructionAspectDismiss => Construct(0xd96);
        public static FormLink<IBookGetter> SCConstructionAspectTeleport => Construct(0xd97);
        public static FormLink<IBookGetter> SCConstructionAspectCure => Construct(0xd98);
        public static FormLink<IBookGetter> SCConstructionAspectDetect => Construct(0xd99);
        public static FormLink<IBookGetter> SCConstructionAspectResist => Construct(0xd9a);
        public static FormLink<IBookGetter> SCConstructionAspectDrain => Construct(0xd9b);
        public static FormLink<IBookGetter> SCConstructionAspectFortify => Construct(0xd9c);
        public static FormLink<IBookGetter> SCConstructionAspectAbsorb => Construct(0xd9d);
        public static FormLink<IBookGetter> SCConstructionAspectWard => Construct(0xd9e);
    }
}
