// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE;

public static partial class SpellConstruction
{
    public static class MiscItem
    {
        private static FormLink<IMiscItemGetter> Construct(uint id) => new FormLink<IMiscItemGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMiscItemGetter> SCSpellbookMisc => Construct(0x3362);
        public static FormLink<IMiscItemGetter> SCCraftingReset => Construct(0x2dff);
    }
}
